package com.example.webmailcore.enums;

public enum MailTemplateType {
    MAIL_TEMPLATE_REGISTRATION,
    MAIL_TEMPLATE_FORGOT_PASSWORD,
    MAIL_TEMPLATE_NOTIFY_ADMINISTRATORS,
    MAIL_TEMPLATE_SEND_INVITATION,
    MAIL_TEMPLATE_SEND_INVITATION_USER,
    MAIL_TEMPLATE_SEND_REFERENCE_NUMBER,
    MAIL_TEMPLATE_CONTACT_SUPPLIER,
    MAIL_TEMPLATE_SEND_MULTIPLE_REFERENCE_NUMBERS,
    MAIL_TEMPLATE_SIGNATURE
}
